"""Initial clean slate

Revision ID: 5fd1c16208f5
Revises: 
Create Date: 2025-05-16 09:39:45.981884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd1c16208f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('player_id', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('player_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(length=80), nullable=False),
    sa.Column('receiver_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.username'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('friend_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.username'], )
    )
    op.create_table('restricted_friends',
    sa.Column('player_id', sa.String(length=80), nullable=False),
    sa.Column('restricted_friends', sa.String(length=200), nullable=True),
    sa.Column('data_sharing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('stats',
    sa.Column('player_id', sa.String(length=80), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('Kd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('restricted_friends')
    op.drop_table('friends')
    op.drop_table('friend_request')
    op.drop_table('user')
    # ### end Alembic commands ###
