"""empty message

Revision ID: 8f42fc3e3b7d
Revises: d5f4edee127a
Create Date: 2025-05-14 10:02:55.160975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f42fc3e3b7d'
down_revision = 'd5f4edee127a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('player_id', sa.String(length=80), nullable=False),
    sa.Column('friend_list', sa.PickleType(), nullable=True),
    sa.Column('allow_friend_sharing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
