"""empty message

Revision ID: d5f4edee127a
Revises: 82a27084a5ba
Create Date: 2025-05-14 09:07:07.709619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f4edee127a'
down_revision = '82a27084a5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('player_id', sa.String(length=80), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('Kd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    op.drop_table('stats')
    # ### end Alembic commands ###
