"""empty message

Revision ID: fb3712d52ef4
Revises: d5f4edee127a
Create Date: 2025-05-15 12:36:40.740064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3712d52ef4'
down_revision = 'd5f4edee127a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricted_friends',
    sa.Column('player_id', sa.String(length=80), nullable=False),
    sa.Column('restricted_friends', sa.String(length=200), nullable=True),
    sa.Column('data_sharing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['user.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_friends')
    # ### end Alembic commands ###
